Metadata api client to UpdateStatus
infratographer/metadata-api pull request #65
Opened 2023-10-12 23:40 UTC by rizzza

# Summary

A go client to update metadata nodeID status for a given namespace

```
mutation StatusUpdate {
  statusUpdate(input: {
    data: "{\"state\":\"ACTIVE\"}"
    namespaceID: "metasns-sLfRL6ejS_ugBOEjeA1SA"
    nodeID:"loadbal-test"
    source:"operator"
  }) {
    status {
      id
      data
      source
      statusNamespaceID

      metadata {
        id
        nodeID 
      }
    }
  }
}
```

```
{
  "data": {
    "statusUpdate": {
      "status": {
        "id": "metasts-rkS5AFiIRNDCg1AUKW4KF",
        "data": {
          "state": "ACTIVE"
        },
        "source": "operator",
        "statusNamespaceID": "metasns-sLfRL6ejS_ugBOEjeA1SA",
        "metadata": {
          "id": "metadat-dfmvVAezsT27wb1i_lxH_",
          "nodeID": "loadbal-test"
        }
      }
    }
  }
}
```

2023-10-17 18:24 UTC, tylerauerbeck requested changes

2023-10-17 18:31 UTC, rizzza commented on internal/graphapi/status.resolvers.go
> +	if err := permissions.CheckAccess(ctx, input.NamespaceID, actionMetadataStatusNamespaceUpdate); err != nil {
most definitely need to fix that

2023-10-17 18:33 UTC, rizzza commented on internal/graphapi/status.resolvers.go
> -					return nil, err
Talking with @jnschaeffer, it was recommended to go after simpler permissions, rather than more fine-grained permissions initially.

2023-10-17 19:29 UTC, rizzza commented on internal/graphapi/status.resolvers.go
> +	if err := permissions.CheckAccess(ctx, input.NamespaceID, actionMetadataStatusNamespaceUpdate); err != nil {
I did definitely put the permissions check in the wrong place messing around here. That needs to go before the `StatusNamespace.Get`. 

I'd prefer to have the input checks happen before attempting to verify the namespace permission. If I were consuming an api, and I kept on getting `subject does not have access`, and it was due to invalid inputs, I'd like to know that before heading down some other path.

2023-10-18 14:16 UTC, tylerauerbeck approved these changes

2023-10-18 14:16 UTC, merged